language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.3.0
dist: trusty
sudo: required

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d0b6810b27cca9a0e15
    on_success: change
    on_failure: always
    on_start: never

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
install: bundle install --jobs=3 --retry=3
script: rake build
